# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sunjay Varma
description: >- # this means to ignore newlines until "baseurl:"
  Sunjay Varma is building open-source software and trying to make programming
  more accessible to the masses.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sunjay.dev" # the base hostname & protocol for your site
twitter_username: sunjay03
github_username:  sunjay

minima:
  social_links:
    twitter: sunjay03
    github: sunjay

google_analytics: "UA-22315778-1"

header_pages:
  - blog/index.md
  - title: Resume
    url: https://sunjay.dev/resume/
  - title: GitHub
    url: https://github.com/sunjay/
  - title: Twitter
    url: https://twitter.com/sunjay03
  - contact.html

# Build settings
markdown: kramdown
theme: minima
permalink: /:year/:month/:day/:title

plugins:
  - jekyll-feed

include:
  - .well-known

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
