# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sunjay Varma
tagline: Let's build something amazing.
email: varma.sunjay@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Let's build something amazing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sunjay.ca" # the base hostname & protocol for your site

# Pagination of blog
paginate: 10
paginate_path: "/blog/:num/"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
